{
  "openapi": "3.0.1",
  "info": {
    "title": "Auth",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/base_url/api/Auth/login": {
      "post": {
        "summary": "Login",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "jana.ayoub.004@gmail.com",
                "password": "Pass@1234"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY1MTRhYjJlLWZjYzItNDY5My1hNTQ1LThiMzAyOWNiZjMxYyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImphbmEuYXlvdWIuMDA0QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NzU1MTM3MTksImlzcyI6IkF1dG9yaWFBUEkiLCJhdWQiOiJBdXRvcmlhQ2xpZW50In0.zeRGgwf40p7qtwPkKllJn6TGNPb9qbLL4BlYvYiE0K0",
                  "refreshToken": "053194d0-7ba0-49aa-9407-379107463c3c",
                  "expiresAt": "2026-04-06T22:15:19.0657882Z"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/base_url/api/Auth/register": {
      "post": {
        "summary": "Register",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "FullName": "John Doe",
                "Email": "john.doe@example.com",
                "Password": "StrongPassword123!",
                "ConfirmPassword": "StrongPassword123!",
                "PhoneNumber": "+201234567890"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImYyYWUyYzFiLWVhZmQtNDdkYi1hYTE2LTIyODI5YTJlMDNlZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzc1NTIyMDM1LCJpc3MiOiJBdXRvcmlhQVBJIiwiYXVkIjoiQXV0b3JpYUNsaWVudCJ9.mcyt2G3-vS8vP5yerq70F11NXw_QkBQNEstVlTPt9Jo",
                  "refreshToken": {
                    "id": "92af3b04-889d-46a1-b595-370e2f817256",
                    "token": "d93d60b5-a355-4eca-8b06-ceebd5cd3caa",
                    "createdAt": "2026-04-06T23:33:55.1931579Z",
                    "expiresAt": "2026-04-13T23:33:55.1927057Z",
                    "isRevoked": false,
                    "userId": "f2ae2c1b-eafd-47db-aa16-22829a2e03ef"
                  },
                  "expiresAt": "2026-04-07T00:33:55.1205205Z"
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/forgetPass": {
      "post": {
        "summary": "Forgot password",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "Email": "jana.ayoub.004@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {}
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/ResetPass": {
      "post": {
        "summary": "Reset Password",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "jana.ayoub.004@gmail.com",
                "token": "token-from-url",
                "newPassword": "123456",
                "confirmPassword": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/logout": {
      "post": {
        "summary": "logout",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "RefreshToken": "4b749c3f-f0a1-45ce-a3a8-38803d4c879b"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "message": "Logged out successfully"
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/resend-verification": {
      "post": {
        "summary": "Resend verification email ",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "email": "jana.ahmad.presentation@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": "Verification email sent"
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/verify-email": {
      "post": {
        "summary": "verify-email",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "token": "CfDJ8Pticvz2Q3dFjGlwDRkO1TJITkF0dMSq0d%2FNuSfJ7ThFNJh67XX%2BvjyoLJPIV%2BCy3g2%2FWpK13Ir7oZUQXIbM9NWGAw7SdrKjCzzNcIVzgmcGyQdgZjeo817PzeqX%2BizN%2FdbR1rAv3Q%2BXgJuWEkFpBedhC0pCXNiIZOWA5lkrCAF4KLyTL8C0%2BdXhMLFvwWKim7St8qA9j4hayc2eObLJleEYo5XD8ZgD9C8%2BJaJglcMPvkP9JZMwgkP%2Bz6jEBJquGA%3D%3D",
                "email": "jana.ahmad.presentation@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": "System.Exception: Email already verified\r\n   at Autoria.features.auth.Commands.VerifyEmail.VerifyEmailHandler.Handle(VerifyEmailCommand request, CancellationToken cancellationToken) in C:\\Users\\Dell\\Source\\Repos\\Autoria\\backend\\Autoria\\features\\auth\\Commands\\VerifyEmail\\VerifyEmailHandler.cs:line 26\r\n   at Autoria.features.auth.AuthController.VerifyEmail(VerifyEmailCommand command) in C:\\Users\\Dell\\Source\\Repos\\Autoria\\backend\\Autoria\\features\\auth\\AuthController.cs:line 76\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)\r\n\r\nHEADERS\r\n=======\r\nAccept: */*\r\nConnection: keep-alive\r\nHost: localhost:5236\r\nUser-Agent: Apidog/1.0.0 (https://apidog.com)\r\nAccept-Encoding: gzip, deflate, br\r\nContent-Type: application/json\r\nContent-Length: 356\r\n"
              }
            }
          }
        },
        "security": []
      }
    },
    "/changePassword": {
      "patch": {
        "summary": "changePassword",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "oldPassword": "Password@333",
                "newPassword": "Pass@1234",
                "confirmPassword": "Pass@1234"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": "password changed successfully"
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/AddAdmin": {
      "post": {
        "summary": "Add Admin",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "fullName": "joy",
                "email": "joy@gmail.com",
                "password": "Password@123",
                "phoneNumber": "Password@123"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Success",
                  "data": "admin added successfully",
                  "errors": null
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/refresh-token": {
      "post": {
        "summary": "refresh-token",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "RefreshToken": "ab239c99-e7e3-4cd1-b920-26b808704767"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Success",
                  "data": {
                    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI2YTZiZTkzLWVjYWYtNDlmMS1iZWY3LThmN2Y4ZTJhOTc1YyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5uLmRvZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3Nzc4OTc1MzMsImlzcyI6IkF1dG9yaWFBUEkiLCJhdWQiOiJBdXRvcmlhQ2xpZW50In0.iAzDKhDwA-watzEXQqwP1bud0RmiBxckD8V-NN8riPw",
                    "refreshToken": {
                      "id": "7887b378-028f-4243-8860-2bd73695da75",
                      "token": "434e1a49-89e5-4d2b-9c31-35e45c191418",
                      "createdAt": "2026-05-04T11:25:33.9770702Z",
                      "expiresAt": "2026-05-11T11:25:33.9764915Z",
                      "isRevoked": false,
                      "userId": "26a6be93-ecaf-49f1-bef7-8f7f8e2a975c"
                    },
                    "expiresAt": "2026-05-04T12:25:33.9000972Z"
                  },
                  "errors": null
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "ChangePasswordCommand": {
        "type": "object",
        "properties": {
          "oldPassword": {
            "type": "string",
            "nullable": true
          },
          "newPassword": {
            "type": "string",
            "nullable": true
          },
          "confirmPassword": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ForgetPassCommand": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "LoginCommand": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "nullable": true
          },
          "password": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "LogoutCommand": {
        "type": "object",
        "properties": {
          "refreshToken": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "RegisterCommand": {
        "type": "object",
        "properties": {
          "fullName": {
            "type": "string",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "password": {
            "type": "string",
            "nullable": true
          },
          "confirmPassword": {
            "type": "string",
            "nullable": true
          },
          "phoneNumber": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ResendVerificationEmailCommand": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ResetPassCommand": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "nullable": true
          },
          "token": {
            "type": "string",
            "nullable": true
          },
          "password": {
            "type": "string",
            "nullable": true
          },
          "confirmPassword": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "VerifyEmailCommand": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "nullable": true
          },
          "token": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    },
    "responses": {},
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [],
  "security": []
}